[package]
name = "car-utils"
version.workspace = true
edition = "2021"
authors = ["Join.Gong<joinhack@gmail.com>", "Derek Anderson<derek@txlabs.org>", "Zeeshan.Sarwar<zeeshan@txlabs.org>"]
description = "This crate is the ipfs car file reader writer and utils CLI."
license = "MIT/Apache-2.0"
publish = true
homepage = "https://github.com/blocklessnetwork"
repository = "https://github.com/blocklessnetwork/car-utils"

[dependencies]
clap = { version = "4.3.19", features = ["derive"] }
blockless-car.workspace = true
multicodec = "0.1.0"
